### ISSUE TITLE
from typing import ( ImportError: cannot import name 'Type'

### ISSUE THREAD

**Issue by bhavandar** [bhavandar/leaf-diseases-predition#1]
I have cloned the repo and pasted the required ML models in a new folder named 'models'. 
When I run 'run.py' and choose Tensorflow or Keras, I get this error:

> C:\Program Files (x86)\Python35-64\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Program Files (x86)\Python35-64\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Program Files (x86)\Python35-64\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Program Files (x86)\Python35-64\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Program Files (x86)\Python35-64\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Program Files (x86)\Python35-64\lib\site-packages\tensorflow\python\framework\dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\nmule\Downloads\leaf-diseases-predition\app\gui.py", line 87, in Analyze
    self.hdf5Model()
  File "C:\Users\nmule\Downloads\leaf-diseases-predition\app\gui.py", line 146, in hdf5Model
    text = self.hdf5Processing(4)
  File "C:\Users\nmule\Downloads\leaf-diseases-predition\app\progress.py", line 53, in decorator
    raise exception
  File "C:\Users\nmule\Downloads\leaf-diseases-predition\app\progress.py", line 39, in run
    result = func(*args, **kwargs)
  File "C:\Users\nmule\Downloads\leaf-diseases-predition\app\gui.py", line 131, in hdf5Processing
    from hdf5.main import index
  File "C:\Users\nmule\Downloads\leaf-diseases-predition\hdf5\main.py", line 3, in <module>
    from keras.models import load_model
  File "C:\Program Files (x86)\Python35-64\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Program Files (x86)\Python35-64\lib\site-packages\keras\utils\__init__.py", line 27, in <module>
    from .multi_gpu_utils import multi_gpu_model
  File "C:\Program Files (x86)\Python35-64\lib\site-packages\keras\utils\multi_gpu_utils.py", line 7, in <module>
    from ..layers.merge import concatenate
  File "C:\Program Files (x86)\Python35-64\lib\site-packages\keras\layers\__init__.py", line 4, in <module>
    from ..engine.base_layer import Layer
  File "C:\Program Files (x86)\Python35-64\lib\site-packages\keras\engine\__init__.py", line 8, in <module>
    from .training import Model
  File "C:\Program Files (x86)\Python35-64\lib\site-packages\keras\engine\training.py", line 21, in <module>
    from . import training_arrays
  File "C:\Program Files (x86)\Python35-64\lib\site-packages\keras\engine\training_arrays.py", line 8, in <module>
    from scipy.sparse import issparse
  File "C:\Program Files (x86)\Python35-64\lib\site-packages\scipy\__init__.py", line 156, in <module>
    from . import fft
  File "C:\Program Files (x86)\Python35-64\lib\site-packages\scipy\fft\__init__.py", line 76, in <module>
    from ._basic import (
  File "C:\Program Files (x86)\Python35-64\lib\site-packages\scipy\fft\_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "C:\Program Files (x86)\Python35-64\lib\site-packages\scipy\_lib\uarray.py", line 27, in <module>
    from ._uarray import *
  File "C:\Program Files (x86)\Python35-64\lib\site-packages\scipy\_lib\_uarray\__init__.py", line 114, in <module>
    from ._backend import *
  File "C:\Program Files (x86)\Python35-64\lib\site-packages\scipy\_lib\_uarray\_backend.py", line 1, in <module>  
from typing import (
ImportError: cannot import name 'Type'

`Process finished with exit code 0`

I am using python 3.5

**Comment by PuneethReddyHC** [comment]
What Tensorflow version you're using?

**Comment by bhavandar** [comment]
Tensorflow version: 1.12.0

P.S: I have changed path in line 3 of deleteimages.py file from
`C:\Users\punehemukeeru\Documents\1Aplantdiseases\pyqt-gui-template\tests`
to 
`C:\Users\nmule\Downloads\leaf-diseases-predition\tests`
because I was getting an error.

**Comment by PuneethReddyHC** [comment]
Install 
pip install Pillow

**Comment by bhavandar** [comment]
Pillow==5.4.0 is already installed.

**Comment by bhavandar** [comment]
**issue fixed**
I was using Python 3.5 and the typing library works with 3.6 and above.
I used Python 3.7 and it worked.

_The tensorflow option works fine but there is still an error in the segment option_
